### In this notebook we try to test different initial conditions for the optimization algorithms. Be careful : this notebook take a lot of time to run entirely (≈ 30 min)

In [8]:
cd(@__DIR__)
include("../utils/utils.jl")

MAPE (generic function with 2 methods)

### Initial conditions

In [9]:
Φ_init=[-100,-1,0,1e-5,1,5,10,100,1000]
σ_init=[1e-10,1e-5,0.1,1,5,50,100,1000,10000]

9-element Vector{Float64}:
     1.0e-10
     1.0e-5
     0.1
     1.0
     5.0
    50.0
   100.0
  1000.0
 10000.0

Making a calendar of 100 years

In [10]:
try 
    using Dates
catch ; 
    import Pkg
    Pkg.add("Dates")
    using Dates
end
k=100
DatesRange=collect(Date(1900):Day(1):Date(1900+k))
N=length(DatesRange)

36525

## Simulating a series following an AR(1) model

In [11]:
x0=7.
Φ,σ=0.7,4.

(0.7, 4.0)

Simulating the series

In [12]:
include("../utils/Simulation.jl")
x=[x0 ; simulation(x0,Φ,σ,N-1)]

36525-element Vector{Float64}:
  7.0
 -0.7823190074480939
  0.5870647132724636
  6.491947434579019
  0.6042852651022028
 -4.80090942589429
  2.9613300363414994
  7.108664014642528
 14.085565594811808
  7.299133790710543
  ⋮
  3.637946699214281
  1.3440343736573401
  3.6691469956990863
  0.574364733094592
  7.007298626327332
  6.187947824575876
  8.605697421566306
  8.1479638422418
  6.017144581922489

# Testing the initial parameters with Nelder-Mead algorithm

In [13]:
include("../utils/Estimation.jl")
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init)

9×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0        -1.0      0.0          1.0e-5       ⋯
     │ Float64               Float64       Float64   Float64      Float64      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │              1.0e-10   0.70062       0.70062   0.70062      0.70062     ⋯
   2 │              1.0e-5    0.70062       0.70062   0.70062      0.700621
   3 │              0.1       0.70062       0.70062   0.70062      0.70062
   4 │              1.0       0.70062       0.70062   0.70062      0.70062
   5 │              5.0       0.70062       0.70062   0.700621     0.70062     ⋯
   6 │             50.0       0.70062       0.70062  -0.00148471  -0.001475
   7 │            100.0      -1.24699e151   2.26143  -0.00648818  -0.00647947
   8 │           1000.0      -1.41951e151  -2.91732   0.0295357    0.0295516
   9 │          10000.0      45.3612       -2.21945  -0.0100691   -0.0100612   ⋯
                                                               5 columns omitted

We notice that estimated Φ values change completely for σ_init² ≥ 50

In [14]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init, sigma_est=true)

9×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0       -1.0         0.0          1.0e-5     ⋯
     │ Float64               Float64      Float64      Float64      Float64    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │              1.0e-10  4.01911      4.01912      4.01911      4.01911    ⋯
   2 │              1.0e-5   4.01911      4.01911      4.01911      4.01911
   3 │              0.1      4.01911      4.01911      4.01911      4.01911
   4 │              1.0      4.01911      4.01911      4.01911      4.01911
   5 │              5.0      4.01911      4.01911      4.01911      4.01911    ⋯
   6 │             50.0      4.01911      4.01912      1.41082e-67  1.41082e-6
   7 │            100.0      6.75263e75   1.63075e-61  5.05901e-69  5.05901e-6
   8 │           1000.0      2.65372e76   4.75802e-68  8.11865e-68  8.11865e-6
   9 │          10000.0      3.49503e-66  1.71888e-65  3.25766e-64  3.25766e-6 ⋯
                                                               6 columns omitted

For σ_init² ≥ 50, estimated σ values are aberrant. 
However, for both Φ and σ estimations, the values remain constant as long as σ_init² < 50 (maybe there is a critical value).
Φ_init doesn't seem to have an impact on the result, except for σ_init = 50 where for some Φ_init the estimation didn't become unstable.
Below we try to find this treshold of instability.

In [15]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init, σ, sigma_est=true)

9×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0        -1.0        0.0         1.0e-5      ⋯
     │ Float64               Float64       Float64     Float64     Float64     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │              1.0e-10    0.477822      0.477911    0.477814    0.477867  ⋯
   2 │              1.0e-5     0.477874      0.477836    0.477863    0.477819
   3 │              0.1        0.477852      0.477856    0.47785     0.477847
   4 │              1.0        0.477837      0.477853    0.477839    0.477828
   5 │              5.0        0.477836      0.477796    0.477872    0.477841  ⋯
   6 │             50.0        0.477848      0.477879  100.0       100.0
   7 │            100.0        1.68816e77  100.0       100.0       100.0
   8 │           1000.0        6.6343e77   100.0       100.0       100.0
   9 │          10000.0      100.0         100.0       100.0       100.0       ⋯
                                                               5 columns omitted

In [16]:
σ_init2=collect(5:10:50)
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init2)

5×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0    -1.0      0.0         1.0e-5      1.0   ⋯
     │ Int64                 Float64   Float64   Float64     Float64     Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                    5  0.70062    0.70062   0.700621    0.70062    0.700 ⋯
   2 │                   15  0.70062    0.70062   0.70062     0.70062    0.700
   3 │                   25  0.340408   0.70062   0.70062     0.70062    0.700
   4 │                   35  0.70062   -1.18468   0.357947    0.358029   2.779
   5 │                   45  0.70062   -1.66323  -0.0115803  -0.0115726  3.308 ⋯
                                                               5 columns omitted

In [17]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init2, sigma_est=true)

5×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0       -1.0         0.0          1.0e-5     ⋯
     │ Float64               Float64      Float64      Float64      Float64    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                  5.0  4.01911      4.01911      4.01911      4.01911    ⋯
   2 │                 15.0  4.01911      4.01911      4.01911      4.01911
   3 │                 25.0  2.49124e-64  4.01911      4.01912      4.01911
   4 │                 35.0  4.01911      2.66145e-59  8.1225e-63   8.1225e-63
   5 │                 45.0  4.01911      3.6596e-65   6.41548e-69  6.41548e-6 ⋯
                                                               6 columns omitted

Unstable values appear for σ_init² ≥ 15. 
Let's try a finer search : 

In [18]:
σ_init3=collect(5:1:15)
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init3)

11×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0   -1.0      0.0       1.0e-5    1.0        ⋯
     │ Int64                 Float64  Float64   Float64   Float64   Float64    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                    5  0.70062  0.70062   0.700621  0.70062   0.70062    ⋯
   2 │                    6  0.70062  0.70062   0.700621  0.70062   0.70062
   3 │                    7  0.70062  0.70062   0.70062   0.70062   0.70062
   4 │                    8  0.70062  0.700621  0.70062   0.70062   0.70062
   5 │                    9  0.70062  0.700621  0.732795  0.732951  0.70062    ⋯
   6 │                   10  0.70062  0.700621  0.70062   0.70062   0.70062
   7 │                   11  0.70062  0.70062   0.700621  0.70062   0.70062
   8 │                   12  0.70062  0.70062   0.70062   0.70062   0.70062
   9 │                   13  0.70062  0.70062   0.70062   0.70062   0.700621   ⋯
  10 │                   14  0.70062  0.70062   0.70062   0.70062   0.70062
  11 │                   15  0.70062  0.70062   0.70062   0.70062   0.70062
                                                               4 columns omitted

In [19]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init3, sigma_est=true)

11×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0   -1.0     0.0          1.0e-5       1.0   ⋯
     │ Float64               Float64  Float64  Float64      Float64      Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                  5.0  4.01911  4.01911  4.01911      4.01911      4.019 ⋯
   2 │                  6.0  4.01911  4.01911  4.01911      4.01911      4.019
   3 │                  7.0  4.01911  4.01911  4.01911      4.01911      4.019
   4 │                  8.0  4.01911  4.01911  4.01911      4.01911      4.019
   5 │                  9.0  4.01911  4.01911  2.14078e-62  2.14078e-62  4.019 ⋯
   6 │                 10.0  4.01911  4.01911  4.01911      4.01911      4.019
   7 │                 11.0  4.01911  4.01911  4.01911      4.01911      4.019
   8 │                 12.0  4.01911  4.01911  4.01911      4.01911      4.019
   9 │                 13.0  4.01911  4.01911  4.01911      4.01911      4.019 ⋯
  10 │                 14.0  4.01911  4.01911  4.01911      4.01911      4.019
  11 │                 15.0  4.01911  4.01911  4.01911      4.01911      4.019
                                                               5 columns omitted

Unstable values appear for σ_init² ≥ 9

For stable values, let's see if the initial conditions have an impact on the accuracy of estimation : 

In [20]:
σ_init4=[1e-5 ; collect(1:2:7)]
println("MAPE table (percentage) :")
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init4, Φ)

MAPE table (percentage) :


5×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0     -1.0       0.0        1.0e-5     1.0   ⋯
     │ Float64               Float64    Float64    Float64    Float64    Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  0.0885718  0.0886136  0.0885482  0.0886572  0.088 ⋯
   2 │               1.0     0.0885898  0.0885811  0.0886285  0.0886062  0.088
   3 │               3.0     0.0886944  0.0885162  0.0885761  0.0886512  0.088
   4 │               5.0     0.0885992  0.0886356  0.0886724  0.0885825  0.088
   5 │               7.0     0.0885704  0.0886055  0.0886269  0.0885924  0.088 ⋯
                                                               5 columns omitted

In [21]:
println("MAPE table (percentage) :")
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init4, sigma_est=true, σ)

MAPE table (percentage) :


5×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0    -1.0      0.0       1.0e-5    1.0       ⋯
     │ Float64               Float64   Float64   Float64   Float64   Float64   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  0.477874  0.477836  0.477863  0.477819  0.477847  ⋯
   2 │               1.0     0.477837  0.477853  0.477839  0.477828  0.477818
   3 │               3.0     0.477857  0.477829  0.477826  0.477896  0.47789
   4 │               5.0     0.477836  0.477796  0.477872  0.477841  0.477835
   5 │               7.0     0.477829  0.477834  0.477806  0.477836  0.477836  ⋯
                                                               4 columns omitted

# AR model on each month

Parameters for each month

In [22]:
Φ_month=[4,1,8,2,7,9,2,4,1,3,1,2]/10
σ_month=[1.5,2,4.5,7,8,3,4.5,1,7,2.5,3,6]

12-element Vector{Float64}:
 1.5
 2.0
 4.5
 7.0
 8.0
 3.0
 4.5
 1.0
 7.0
 2.5
 3.0
 6.0

Generating the series associated

In [23]:
n_month=200
x=SimulateMonth(4.,Date(2000,11,1),Φ_month,σ_month,n_month)
Date_vec=collect(Date(2000,11,1):(Date(2000,11,1) + Month(n_month) - Day(1)))

6086-element Vector{Date}:
 2000-11-01
 2000-11-02
 2000-11-03
 2000-11-04
 2000-11-05
 2000-11-06
 2000-11-07
 2000-11-08
 2000-11-09
 2000-11-10
 ⋮
 2017-06-22
 2017-06-23
 2017-06-24
 2017-06-25
 2017-06-26
 2017-06-27
 2017-06-28
 2017-06-29
 2017-06-30

Separation of the months

In [24]:
include(raw"..\utils\Separation.jl")
Monthly_date=MonthlySeparateDates(Date_vec)
Monthly_temp=MonthlySeparateX(x,Date_vec)

12-element Vector{Vector{Any}}:
 [[-0.8742944132189718, 1.5380226629411402, -1.374460472739487, -2.087856965374933, -2.0533668399300287, -0.3068925752715106, -2.7521921183823985, -0.8070469337985233, -1.0736089890502973, -3.557841118578305  …  1.1798558912780837, 0.2131769888633976, -1.1706064304341077, 2.1506065138016894, 0.9420866218324002, -2.0753514051652653, -2.7180033262916705, -0.4868430263627238, -1.3479349432416734, -0.1515956203150729], [-2.163280511528164, -0.44066377383437827, 0.07107063258357277, -0.7661473587961299, -0.5242290002702481, 0.17265018710402233, 0.4861793776198813, -2.802644771992067, -2.5827357603200074, -1.1475143579981693  …  0.023626879836710024, -0.969215304976802, 2.277163491670322, 2.6587509715164703, 0.9231820005671857, 2.103756383497975, 0.8747137172400139, 1.0621660512911657, -0.9865727591690163, 2.1553435464274284], [2.5723743086615523, 1.9136173690672296, 2.6013373734188514, 0.6280794670128926, -0.7129397360724437, -1.692263802710891, -1.4174342833

## 1.One model per year and per month

In [25]:
MeanMonthlyEstimation(x,p,Estimators::Vector=[zeros(p) ; 1e-5],algo=NelderMead())=
(Monthly_stats(mean,MonthlyEstimation(Monthly_temp,p,Estimators,algo),1),
Monthly_stats(mean,MonthlyEstimation(Monthly_temp,p,Estimators,algo),2))

MeanMonthlyEstimation (generic function with 3 methods)

In [26]:
Monthly_Estimators=MonthlyEstimation(Monthly_temp,1)

12-element Vector{Vector{Any}}:
 [(0.2571643972039014, 1.4942433066529743), (0.37501804629518415, 1.342344408594641), (0.5910713222795357, 1.786164666840303), (0.22258981318501508, 1.3708262651331538), (0.30246733134360404, 1.8779603168347554), (0.2456979518602695, 1.677098374990132), (0.7153270129070535, 1.425627059921448), (0.31227809368739995, 1.2103642806258743), (0.020850391804022185, 1.167688007758888), (0.3029030390696757, 1.5343280738923628), (0.2971385936885589, 1.6167261382937015), (0.22437131257734988, 1.4721712311695823), (0.551295125681446, 1.5069044656486708), (0.2654473489085167, 1.8815730909741657), (0.2643617357666759, 1.4926247528064558), (0.5191549764367509, 1.3871174587591), (0.48256957203823503, 1.3358743107654707)]
 [(0.12083231527990776, 2.281281350143772), (0.33122847541278144, 1.8930852751977527), (-0.10542438282834422, 1.831469125550127), (0.27890434024196187, 1.880164510656696), (0.17386300708029978, 2.052935173060575), (0.3361169730854379, 1.912345877290476)

In [27]:
Monthly_stats(mean,Monthly_Estimators,1)

12-element Vector{Any}:
 0.34998270969018785
 0.11382110485983733
 0.7551940487106338
 0.2587444494422747
 0.6248129617495133
 0.8707422119469506
 0.14510022135366493
 0.4082198128748544
 0.06314900240449156
 0.3695891136303688
 0.014578604015184016
 0.20262471425406822

In [28]:
MeanMonthlyEstimation(Monthly_Estimators,1)

(Any[0.34998270969018785, 0.11382110485983733, 0.7551940487106338, 0.2587444494422747, 0.6248129617495133, 0.8707422119469506, 0.14510022135366493, 0.4082198128748544, 0.06314900240449156, 0.3695891136303688, 0.014578604015184016, 0.20262471425406822], Any[1.5046844829212753, 1.8872691189541058, 4.657554458902432, 6.885282199523715, 7.859424214436346, 2.875521226420322, 4.3708110201400086, 0.9964028817837451, 6.276522439825367, 2.360667561140532, 3.025664280104385, 5.514798750187526])

In [29]:
σ_init=[1e-5,1,3,5,7,9,15,50]

8-element Vector{Float64}:
  1.0e-5
  1.0
  3.0
  5.0
  7.0
  9.0
 15.0
 50.0

In [30]:
GridEstimation(MeanMonthlyEstimation, Monthly_temp , Φ_init, σ_init)

8×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0                             -1.0           ⋯
     │ Float64               Array…                             Array…         ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  Any[0.349984, 0.11382, 0.755191,…  Any[0.349985,  ⋯
   2 │               1.0     Any[0.349988, 0.113828, 0.755194…  Any[0.349982,
   3 │               3.0     Any[0.322648, 0.113823, 0.755197…  Any[0.494368,
   4 │               5.0     Any[1.09711, 0.113819, 0.755194,…  Any[0.415238,
   5 │               7.0     Any[1.4071, 0.335897, 0.755194, …  Any[1.07142, 0 ⋯
   6 │               9.0     Any[1.04877, 0.535205, 0.755195,…  Any[0.531014,
   7 │              15.0     Any[-8.08089e151, 0.62645, 0.755…  Any[-0.497245,
   8 │              50.0     Any[6.67384e151, 8.83706e151, 0.…  Any[-2.5278, -
                                                               8 columns omitted

Reminder : 
```julia
Φ_month=[4,1,8,2,7,9,2,4,1,3,1,2]/10
σ_month=[1.5,2,4.5,7,8,3,4.5,1,7,2.5,3,6]
```

In [31]:
println("MAPE table (percentage) :")
GridEstimation(MeanMonthlyEstimation, Monthly_temp , Φ_init, σ_init, Φ_month)

MAPE table (percentage) :


8×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0        -1.0      0.0      1.0e-5   1.0     ⋯
     │ Float64               Float64       Float64   Float64  Float64  Float64 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  20.965         20.9657  20.9647  20.9642   20.965 ⋯
   2 │               1.0     20.966         20.9663  21.3329  21.3334   20.965
   3 │               3.0     61.7173        25.2578  29.6251  29.6215   22.519
   4 │               5.0     43.2097        26.8023  37.7201  37.721    30.788
   5 │               7.0     98.8435        81.5873  44.971   44.97     91.915 ⋯
   6 │               9.0      5.21364e153  178.145   46.8584  46.8573  141.311
   7 │              15.0      2.07946e154  115.911   46.2079  46.2088  174.602
   8 │              50.0      4.69193e154  593.053   60.4521  60.4445  488.231
                                                               5 columns omitted

Like before, we see that the more σ_init is close to 0 the better is the estimation.

In [32]:
println("MAPE table (percentage) :")
GridEstimation(MeanMonthlyEstimation, Monthly_temp , Φ_init, σ_init, σ_month, sigma_est=true)

MAPE table (percentage) :


8×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0       -1.0      0.0      1.0e-5    1.0     ⋯
     │ Float64               Float64      Float64   Float64  Float64   Float64 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5   3.75649      3.75645   3.7564   3.75646   3.7564 ⋯
   2 │               1.0      3.75639      3.75652  10.308   10.3081    3.7564
   3 │               3.0     12.6873      11.842    23.9474  23.9475   12.3894
   4 │               5.0     15.9034      17.2576   31.511   31.5111   16.4791
   5 │               7.0     22.4361      20.64     39.9732  39.9732   23.0805 ⋯
   6 │               9.0      1.84937e76  27.8045   43.1265  43.1266   27.3457
   7 │              15.0      1.10763e77  37.8253   51.9383  51.9383   36.7391
   8 │              50.0      2.70337e77  65.7651   74.2125  74.2125   64.4186
                                                               5 columns omitted

It is the same for estimating σ.

## 2.Each month concatanated with all years

In [33]:
σ_init=[1e-5,1,3,5,7,9,15,50]
GridEstimation(MonthlyConcatanatedEstimation, Monthly_temp, Φ_init, σ_init)

8×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0                             -1.0           ⋯
     │ Float64               Array…                             Array…         ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  Any[0.347149, 0.111278, 0.777778…  Any[0.347145,  ⋯
   2 │               1.0     Any[0.347153, 0.111276, 0.777778…  Any[0.347159,
   3 │               3.0     Any[0.347157, 0.11127, 0.777774,…  Any[0.347158,
   4 │               5.0     Any[0.34715, 0.111272, 0.777776,…  Any[0.347161,
   5 │               7.0     Any[4.40836, -0.0604806, 0.77777…  Any[1.08129, 0 ⋯
   6 │               9.0     Any[1.24526, -0.952787, 0.777777…  Any[1.05598, 3
   7 │              15.0     Any[1.20953, 1.20953, 0.777779, …  Any[-0.0570791
   8 │              50.0     Any[2.70167, 7.48181, 0.777775, …  Any[-2.5278, -
                                                               8 columns omitted

Values start to fluctuate from σ_init² = 5 for monthly estimation.

In [34]:
σ_init=[1e-5,1,2,3,4,5]
println("MAPE table (percentage) :")
GridEstimation(MonthlyConcatanatedEstimation, Monthly_temp, Φ_init, σ_init, Φ_month)

MAPE table (percentage) :


6×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0   -1.0      0.0      1.0e-5   1.0      5.0 ⋯
     │ Float64               Float64  Float64   Float64  Float64  Float64  Flo ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  22.7096   22.7093  22.7081  22.7093  22.7088   22 ⋯
   2 │               1.0     22.7089   22.7081  22.7097  22.9557  22.7091   22
   3 │               2.0     22.708    22.7087  36.4735  36.4761  22.7087   22
   4 │               3.0     79.0092   26.6092  38.2553  38.2562  35.618    22
   5 │               4.0     51.6385   27.548   31.7082  31.7099  76.562    55 ⋯
   6 │               5.0     54.9316  152.105   50.0758  50.0751  97.6348  363
                                                               4 columns omitted

Values start to fluctuate from σ_init² = 2 for monthly estimation. It seems that in every case the initial value for σ must be close to 0 for best results.

In [35]:
σ_init=[1e-5,1,2,3,4,5]
println("MAPE table (percentage) :")
GridEstimation(MonthlyConcatanatedEstimation, Monthly_temp, Φ_init, σ_init, σ_month, sigma_est=true)

MAPE table (percentage) :


6×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0    -1.0      0.0       1.0e-5    1.0       ⋯
     │ Float64               Float64   Float64   Float64   Float64   Float64   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5   5.87085   5.87078   5.87082   5.87084   5.87085  ⋯
   2 │               1.0      5.87074   5.87082   5.87088  12.268     5.87083
   3 │               2.0      5.87074   5.87075  20.434    20.434     5.87075
   4 │               3.0     14.0368   14.0368   28.1766   28.1766   14.0369
   5 │               4.0     14.0369   14.0369   20.434    20.434    14.0368   ⋯
   6 │               5.0     14.0369   22.1122   35.9602   35.9602   21.8204
                                                               4 columns omitted

When we estimate σ, values became also unsatisfactory from σ_init² = 2.

## 3.One likelihood for each month

In [36]:
σ_init=[1e-5,1,3,5,7,9,15,50]
GridEstimation(MonthlyEstimationSumLL, Monthly_temp, Φ_init, σ_init)

8×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0                             -1.0           ⋯
     │ Float64               Array…                             Array…         ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  Any[0.384404, 0.124502, 0.792455…  Any[0.384403,  ⋯
   2 │               1.0     Any[0.384403, 0.124501, 0.792454…  Any[0.3844, 0.
   3 │               3.0     Any[0.384403, 0.124501, 0.792451…  Any[0.384404,
   4 │               5.0     Any[0.384401, 0.124499, 0.792455…  Any[0.384409,
   5 │               7.0     Any[1.52311, -0.0604806, 0.79245…  Any[1.16546, 0 ⋯
   6 │               9.0     Any[1.24526, -0.952787, 0.792454…  Any[1.05598, 3
   7 │              15.0     Any[-2.1078, 1.20953, 0.792451, …  Any[-0.0570791
   8 │              50.0     Any[2.70167, 7.48181, 0.792452, …  Any[-2.5278, -
                                                               8 columns omitted

Values start to fluctuate from σ_init² = 2 for monthly estimation with sum of likelihood.

In [37]:
σ_init=[1e-5,1,2,3,4,5]
println("MAPE table (percentage) :")
GridEstimation(MonthlyEstimationSumLL, Monthly_temp, Φ_init, σ_init, Φ_month)

MAPE table (percentage) :


6×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0   -1.0     0.0      1.0e-5   1.0      5.0  ⋯
     │ Float64               Float64  Float64  Float64  Float64  Float64  Floa ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5  21.836   21.8263  21.8353  21.8363  21.8369   21. ⋯
   2 │               1.0     21.8363  21.8362  23.2126  23.2113  21.8346   21.
   3 │               2.0     21.8363  21.8359  33.3417  33.34    21.837    29.
   4 │               3.0     78.002   25.6019  37.6299  37.6322  31.6858   24.
   5 │               4.0     50.631   26.5403  38.5639  38.5632  75.5543   54. ⋯
   6 │               5.0     53.9237  83.9598  44.4696  44.4684  88.4242  371.
                                                               4 columns omitted

Here, even from σ_init² = 1 estimations start to be less accurate.

In [38]:
σ_init=[1e-5,1,2,3,4,5]
println("MAPE table (percentage) :")
GridEstimation(MonthlyEstimationSumLL, Monthly_temp, Φ_init, σ_init, σ_month, sigma_est=true)

MAPE table (percentage) :


6×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0    -1.0      0.0       1.0e-5    1.0       ⋯
     │ Float64               Float64   Float64   Float64   Float64   Float64   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5   3.20889   7.7596    3.20866   3.20884   3.2088   ⋯
   2 │               1.0      3.20883   3.2088   11.3491   11.3491    3.20875
   3 │               2.0      3.20893   3.20885  19.6087   19.6087    3.20868
   4 │               3.0     11.4685   11.4684   27.4749   27.475    11.4684
   5 │               4.0     11.4685   11.4686   27.6986   27.6986   11.4683   ⋯
   6 │               5.0     11.4684   11.4684   35.5648   35.5647   11.4684
                                                               4 columns omitted

Just like before, only for σ_init² ≈ 0 estimated parameters do not become very inaccurate.

## Conclusion

Φ_init does not seem to have an significant impact on the quality of estimation of Φ and σ. However, if σ_init is superior or equal to 1, some parameters estimated became very innacurate and the greater σ_init is, the more parameters tend to explode. 

# Testing the initial parameters with BFGS algorithm

In [39]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init[1:3],algo=BFGS())

3×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0      -1.0      0.0       1.0e-5    1.0     ⋯
     │ Float64               Float64     Float64   Float64   Float64   Float64 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │               1.0e-5    -1.39355  0.301968  0.283648  0.269054  0.71228 ⋯
   2 │               1.0     -167.283    0.517915  0.517915  0.517915  0.51791
   3 │               2.0      124.635    0.517915  0.517915  0.517915  0.51791
                                                               5 columns omitted

In [40]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init[4:5],algo=BFGS())

2×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0     -1.0      0.0       1.0e-5    1.0      ⋯
     │ Float64               Float64    Float64   Float64   Float64   Float64  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                  3.0  48.4654    0.517915  0.517915  0.517915  0.517915 ⋯
   2 │                  4.0  -0.200559  0.517915  0.517915  0.517915  0.517915
                                                               4 columns omitted

In [41]:
GridEstimation(LL_AR_Estimation,x, Φ_init, [σ_init[6]],algo=BFGS())

1×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0    -1.0      0.0       1.0e-5    1.0       ⋯
     │ Float64               Float64   Float64   Float64   Float64   Float64   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                  5.0  -98.0109  0.517915  0.517915  0.517915  0.517915  ⋯
                                                               4 columns omitted

Here the BFGS algorithm can be very slow but more importantly the output is far from the true value and change significantly from one initial Φ to another. 

# Testing the initial parameters with Gradient Descent algorithm

In [ ]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init[1:3],algo=GradientDescent())

3×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0       -1.0       0.0       1.0e-5   1.0    ⋯
     │ Float64               Float64      Float64    Float64   Float64  Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │              1.0e-10  -100.0       -1.0       0.0       1.0e-5   1.0    ⋯
   2 │              1.0e-5     25.2559     0.53981   0.301765  0.39506  0.7704
   3 │              0.1         0.696702   0.694819  0.683459  0.65634  0.7114
                                                               5 columns omitted

In [ ]:
GridEstimation(LL_AR_Estimation,x, Φ_init, σ_init[4:5],algo=GradientDescent())

2×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0        -1.0      0.0       1.0e-5    1.0   ⋯
     │ Float64               Float64       Float64   Float64   Float64   Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                  1.0  -410.869      0.696632  0.696756  0.696756  0.697 ⋯
   2 │                  5.0     2.15766e6  0.6968    0.696792  0.696792  0.698
                                                               5 columns omitted

In [ ]:
GridEstimation(LL_AR_Estimation,x, Φ_init, [σ_init[6]],algo=GradientDescent())

1×10 DataFrame
 Row │ σ_init² ↓ | Φ_init →  -100.0   -1.0      0.0      1.0e-5   1.0      5.0 ⋯
     │ Float64               Float64  Float64   Float64  Float64  Float64  Flo ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                 50.0  96555.3  0.689629      0.0   1.0e-5      1.0  0.6 ⋯
                                                               4 columns omitted

The results are very similar to the results given by the BFGS algorithm : a lot of them are inaccurate and the algorithm is very slow. The Nelder-Mead algorithm seems to be the best optimization algorithm for our problem.